version: '3.8'

services:


  mysports2020-db:
    image: ${DB_IMAGE}
    volumes:
      - ${PROGRESS_CFG}:/usr/dlc/progress.cfg
    ports:
      - 10000-10010:10000-10010
    environment:
      - DBNAME=sports2020    
      
  mysports2020-pas:
    image: ${PAS_IMAGE}
    volumes:
      - ${PROGRESS_CFG}:/usr/dlc/progress.cfg
      - ./src:/app/src
      - ./conf/as.pf:/app/config/as.pf
    ports:
      - ${PAS_PORT}:8810
    environment:
      - PASWEBHANDLERS=/app/src/webhandlers/ROOT.handlers
    depends_on:
      - mysports2020-db
    